"""initial schema

Revision ID: 34d63ce4d3a7
Revises: 
Create Date: 2025-09-06 15:06:15.402724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d63ce4d3a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.Column('results', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('numbers', sa.String(), nullable=False),
    sa.Column('jackpot', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_number')
    )
    op.create_table('number_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('total_appearances', sa.Integer(), nullable=False),
    sa.Column('last_appearance', sa.Date(), nullable=True),
    sa.Column('average_gap_days', sa.Float(), nullable=True),
    sa.Column('max_gap_days', sa.Integer(), nullable=True),
    sa.Column('min_gap_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'game_type', name='uq_number_game')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number_statistics')
    op.drop_table('draws')
    op.drop_table('analyses')
    # ### end Alembic commands ###
